In [14]:
import numpy as np
np.__version__

'1.23.3'

In [15]:
list = [1,2,3,4,5]
array = np.array(list)
array

array([1, 2, 3, 4, 5])

In [16]:
array.ndim  #dimencion

1

In [17]:
array.shape #numero de elementos con coma

(5,)

In [18]:
array.size #elemntos de campos sin coma

5

In [20]:
array.dtype #tipo de dato

dtype('int32')

In [21]:
array.itemsize #numero de bits que ocupa la variable

4

In [22]:
array.data #ubicación de memeoria

In [23]:
type(array)

numpy.ndarray

In [24]:
max(array)

5

In [25]:
min(array)

1

In [26]:
array.max()

5

In [27]:
array.min()

1

In [29]:
list_1 = [1,2,3]
list_2 = [4,5,6]
array = np.array([list_1,list_2])

In [30]:
array.ndim

2

In [31]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
array.shape

(2, 3)

In [33]:
array.size

6

In [35]:
array.dtype

dtype('int32')

In [36]:
array.itemsize

4

In [37]:
array.max()

6

In [38]:
array.min()

1

In [50]:
list_1 = [1,2]
list_2 = [3,4,5]
list_3 = [6,7,8,9]
array = np.array([list_1,list_2,list_3], dtype=object)
array

array([list([1, 2]), list([3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [40]:
array.size

3

In [41]:
array.ndim

1

In [42]:
array.itemsize

8

In [43]:
array.shape

(3,)

In [45]:
array

array([list([1, 2]), list([3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [55]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [57]:
array = np.arange(5,10,3)
array

array([5, 8])

In [60]:
array = np.zeros([3,4]) ## crea un array de 3*4 de ceros
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
array = np.ones([4,3]) ## crea un array de 4*3 de unos
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
array = np.linspace(0,5,10)
array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [64]:
array = np.linspace(0,5,3)
array

array([0. , 2.5, 5. ])

In [65]:
array = np.linspace(0,5,4)
array

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [66]:
array = np.linspace(0,10,10)
array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [67]:
array = np.linspace(0,9,10)
array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [70]:
array = np.linspace(0,9,3)
array

array([0. , 4.5, 9. ])