In [1]:
import numpy as np

In [2]:
array = np.array(['Unos',"Dos Dos","Tres"])
array

array(['Unos', 'Dos Dos', 'Tres'], dtype='<U7')

In [3]:
# toma el array el primer elemento lo complementa a 10 espacios y lo intenta centrar
np.char.center(array, 10, '-')

array(['---Unos---', '-Dos Dos--', '---Tres---'], dtype='<U10')

In [4]:
# ace el conteo de cuantas veses aparece una palabra en alguna cadena o lista
np.char.count(array, "os")

array([1, 2, 0])

In [5]:
np.char.find(array,'OS')

array([-1, -1, -1])

In [6]:
np.char.rfind(array, 'os')  # si no lo encuentra nos lanza -1

array([ 2,  5, -1])

In [7]:
np.char.index(array, "s")  # si no lo encuentra nos lanza un error

array([3, 2, 3])

In [8]:
np.char.rindex(array,"s") #busca la s de derecha a izquierda

array([3, 6, 3])

In [9]:
array = np.array(['Hola','3','Hola3',"\t"])
array

array(['Hola', '3', 'Hola3', '\t'], dtype='<U5')

In [10]:
np.char.isalnum(array) #verifica si la cadena contiene caracteres alfa numericos

array([ True,  True,  True, False])

In [11]:
np.char.isalpha(array) #si es texto

array([ True, False, False, False])

In [12]:
np.char.isdecimal(array) #si es decimal 

array([False,  True, False, False])

In [13]:
np.char.isnumeric(array) #si es numerico

array([False,  True, False, False])

In [14]:
np.char.isspace(array) #si contiene espacios

array([False, False, False,  True])

In [15]:
np.char.istitle(array) #si la primer letra es mayuscula

array([ True, False,  True, False])