# Operaciones aritmeticas con Numpy

In [12]:
import numpy as np

In [13]:
list = [1,2]
list

[1, 2]

In [14]:
list * 2 # solo duplica los datos

[1, 2, 1, 2]

In [15]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Suma

In [18]:
arr = np.arange(0,3)
arr

array([0, 1, 2])

In [19]:
arr + 2

array([2, 3, 4])

## Divicion

In [20]:
arr = np.arange(0,3)
arr

array([0, 1, 2])

In [21]:
1/arr

C:\Users\Kevin López\AppData\Local\Temp\ipykernel_16096\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([inf, 1. , 0.5])

## Suma de dos array

In [22]:
arr = np.arange(0,3)
arr

array([0, 1, 2])

In [23]:
arr2 = np.arange(0,3)
arr2

array([0, 1, 2])

In [24]:
arr + arr2

array([0, 2, 4])

## Suma de matrices

In [25]:
arr = np.arange(0,10)
matriz = arr.reshape(2,5)

In [26]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
matriz2 = matriz.copy()

In [28]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

## Producto punto

In [29]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [31]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])